In [3]:
import pandas as pd


a=pd.read_csv(r"C:\Users\HP\Desktop\python projects\healthcareproject\Loan.csv")
a

,ApplicationDate,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,2018-01-01,45,39948,617,Employed,Master,22,13152,48,Married,...,3329.000000,0.724972,11,126928,0.199652,0.227590,419.805992,0.181077,0,49.0
1,2018-01-02,38,39709,628,Employed,Associate,15,26045,48,Single,...,3309.083333,0.935132,3,43609,0.207045,0.201077,794.054238,0.389852,0,52.0
2,2018-01-03,47,40724,570,Employed,Bachelor,26,17627,36,Married,...,3393.666667,0.872241,6,5205,0.217627,0.212548,666.406688,0.462157,0,52.0
3,2018-01-04,58,69084,545,Employed,High School,34,37898,96,Single,...,5757.000000,0.896155,5,99452,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,2018-01-05,37,103264,594,Employed,Associate,17,9184,36,Married,...,8605.333333,0.941369,5,227019,0.197184,0.175990,330.179140,0.070210,1,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2072-09-29,44,30180,587,Employed,High School,19,24521,36,Married,...,2515.000000,0.826217,1,55327,0.216021,0.195574,905.767712,0.627741,0,55.0
19996,2072-09-30,56,49246,567,Employed,Associate,33,25818,36,Married,...,4103.833333,0.816618,3,64002,0.227318,0.199168,958.395633,0.334418,0,54.0
19997,2072-10-01,44,48958,645,Employed,Bachelor,20,37033,72,Married,...,4079.833333,0.887216,3,103663,0.229533,0.226766,945.427454,0.357227,0,45.0
19998,2072-10-02,60,41025,560,Employed,High School,36,14760,72,Married,...,3418.750000,0.843787,5,10600,0.249760,0.264873,411.168284,0.408678,0,59.0
19999,2072-10-03,20,53227,574,Employed,Associate,0,32055,48,Married,...,4435.583333,0.853801,5,41372,0.240055,0.242693,1049.830407,0.298006,0,59.0

In [4]:
x = a[['ApplicationDate', 'Age', 'AnnualIncome', 'CreditScore',
       'EmploymentStatus', 'EducationLevel', 'Experience', 'LoanAmount',
       'LoanDuration', 'MaritalStatus', 'NumberOfDependents',
       'HomeOwnershipStatus', 'MonthlyDebtPayments',
       'CreditCardUtilizationRate', 'NumberOfOpenCreditLines',
       'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory',
       'LoanPurpose', 'PreviousLoanDefaults', 'PaymentHistory',
       'LengthOfCreditHistory', 'SavingsAccountBalance',
       'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities',
       'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth',
       'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment',
       'TotalDebtToIncomeRatio','LoanApproved']]
y = a[["RiskScore"]]

In [13]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ApplicationDate             20000 non-null  int64
 1   Age                         20000 non-null  int64
 2   AnnualIncome                20000 non-null  int64
 3   CreditScore                 20000 non-null  int64
 4   EmploymentStatus            20000 non-null  object
 5   EducationLevel              20000 non-null  object
 6   Experience                  20000 non-null  int64
 7   LoanAmount                  20000 non-null  int64
 8   LoanDuration                20000 non-null  int64
 9   MaritalStatus               20000 non-null  object
 10  NumberOfDependents          20000 non-null  int64
 11  HomeOwnershipStatus         20000 non-null  object
 12  MonthlyDebtPayments         20000 non-null  int64
 13  CreditCardUtilizationRate   20000 non-null  float64
 14  NumberOfOpenCreditLines     20000 non-null  int64
 15  NumberOfCreditInquiries     20000 non-null  int64
 16  DebtToIncomeRatio           20000 non-null  float64
 17  BankruptcyHistory           20000 non-null  int64
 18  LoanPurpose                 20000 non-null  int64
 19  PreviousLoanDefaults        20000 non-null  int64
 20  PaymentHistory              20000 non-null  int64
 21  LengthOfCreditHistory       20000 non-null  int64
 22  SavingsAccountBalance       20000 non-null  int64
 23  CheckingAccountBalance      20000 non-null  int64
 24  TotalAssets                 20000 non-null  int64
 25  TotalLiabilities            20000 non-null  int64
 26  MonthlyIncome               20000 non-null  float64
 27  UtilityBillsPaymentHistory  20000 non-null  float64
 28  JobTenure                   20000 non-null  int64
 29  NetWorth                    20000 non-null  int64
 30  BaseInterestRate            20000 non-null  float64
 31  InterestRate                20000 non-null  float64
 32  MonthlyLoanPayment          20000 non-null  float64
 33  TotalDebtToIncomeRatio      20000 non-null  float64
 34  LoanApproved                20000 non-null  int64
 35  RiskScore                   20000 non-null  float64
dtypes: float64(9), int64(23), object(4)
memory usage: 5.5+ MB

In [19]:
from sklearn.preprocessing import LabelEncoder

h=LabelEncoder()

a['HomeOwnershipStatus'] = h.fit_transform(a['HomeOwnershipStatus'])

In [21]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ApplicationDate             20000 non-null  int64
 1   Age                         20000 non-null  int64
 2   AnnualIncome                20000 non-null  int64
 3   CreditScore                 20000 non-null  int64
 4   EmploymentStatus            20000 non-null  int64
 5   EducationLevel              20000 non-null  int64
 6   Experience                  20000 non-null  int64
 7   LoanAmount                  20000 non-null  int64
 8   LoanDuration                20000 non-null  int64
 9   MaritalStatus               20000 non-null  int64
 10  NumberOfDependents          20000 non-null  int64
 11  HomeOwnershipStatus         20000 non-null  int64
 12  MonthlyDebtPayments         20000 non-null  int64
 13  CreditCardUtilizationRate   20000 non-null  float64
 14  NumberOfOpenCreditLines     20000 non-null  int64
 15  NumberOfCreditInquiries     20000 non-null  int64
 16  DebtToIncomeRatio           20000 non-null  float64
 17  BankruptcyHistory           20000 non-null  int64
 18  LoanPurpose                 20000 non-null  int64
 19  PreviousLoanDefaults        20000 non-null  int64
 20  PaymentHistory              20000 non-null  int64
 21  LengthOfCreditHistory       20000 non-null  int64
 22  SavingsAccountBalance       20000 non-null  int64
 23  CheckingAccountBalance      20000 non-null  int64
 24  TotalAssets                 20000 non-null  int64
 25  TotalLiabilities            20000 non-null  int64
 26  MonthlyIncome               20000 non-null  float64
 27  UtilityBillsPaymentHistory  20000 non-null  float64
 28  JobTenure                   20000 non-null  int64
 29  NetWorth                    20000 non-null  int64
 30  BaseInterestRate            20000 non-null  float64
 31  InterestRate                20000 non-null  float64
 32  MonthlyLoanPayment          20000 non-null  float64
 33  TotalDebtToIncomeRatio      20000 non-null  float64
 34  LoanApproved                20000 non-null  int64
 35  RiskScore                   20000 non-null  float64
dtypes: float64(9), int64(27)
memory usage: 5.5 MB

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,test_size=0.2,random_state=100)

In [20]:
from sklearn.linear_model import LinearRegression


regressor=LinearRegression()


regressor.fit(x_test,y_test)

regressor.predict(x_test)


hi=regressor.score(x_test,y_test)

DS=regressor.score(x_train,y_train)

print(DS*100)
print(hi*100)


ho=regressor.predict(x_test)
print(ho)
ho[0:10]


# To add the colcoumn name for the predicted data set

x_test['Loanapproved_status']=ho

print(x_test)

ValueError: could not convert string to float: '2025-12-27'